import test from 'node:test';
import assert from 'node:assert/strict';
import {vcard,safeLink,cardUrl,emptyProfile,normalizeProfile,qrSvg,validateProfile} from '../src/lib.js';
test('public URLs retain the card identity across content changes',()=>{assert.equal(cardUrl('abc','https://cards.example.fr'), 'https://cards.example.fr/c/abc');assert.equal(cardUrl('a/b','https://cards.example.fr'), 'https://cards.example.fr/c/a%2Fb')});
test('links cannot execute scripts',()=>{for(const link of ['javascript:alert(1)','data:text/html,hello','//evil.test','file:///a'])assert.equal(safeLink(link),'');assert.equal(safeLink('https://github.com/JavaChrist'),'https://github.com/JavaChrist')});
test('vCard escapes injected lines and folds unicode by octet length',()=>{const p={...emptyProfile,firstName:'É'.repeat(80),lastName:'Test\r\nTEL:bad',company:'A;B,C\\D'};const v=vcard(p,'https://example.fr/c/id');assert.ok(v.includes('Test\\nTEL:bad'));assert.ok(v.includes('ORG:A\\;B\\,C\\\\D'));assert.ok(!v.includes('\r\nTEL:bad'));assert.ok(v.split('\r\n').every(line=>Buffer.byteLength(line)<=75));assert.ok(v.endsWith('END:VCARD\r\n'))});
test('untrusted profile types cannot become React children or CSS',()=>{const p=normalizeProfile({firstName:{bad:'object'},accent:'red; background:url(x)',lastName:'Valid'});assert.equal(p.firstName,'');assert.equal(p.lastName,'Valid');assert.equal(p.accent,'#ff941f')});
test('required identity and malformed URLs are validated',()=>{assert.notEqual(validateProfile(emptyProfile),'');assert.equal(validateProfile({...emptyProfile,firstName:'A',lastName:'B'}),'');assert.notEqual(validateProfile({...emptyProfile,firstName:'A',lastName:'B',github:'javascript:bad'}),'')});
test('QR is a standalone vector image without a remote generator',()=>{const svg=qrSvg('https://cards.example.fr/c/a');assert.match(svg,/<svg/);assert.match(svg,/viewBox=/);assert.ok(!svg.includes('<script'));assert.ok(!svg.includes('<image'))});
